const ERROR_CODES = {
    DEVICE_ID_REQUIRED: "DEVICE_ID_REQUIRED",
    TOKEN_MISSING: "TOKEN_MISSING",
    TOKEN_EXPIRED: "TOKEN_EXPIRED",
    TOKEN_INVALID: "TOKEN_INVALID",
    INVALID_DEVICE: "INVALID_DEVICE",
    INVALID_CREDENTIALS: "INVALID_CREDENTIALS",
    ACCOUNT_LOCKED: "ACCOUNT_LOCKED",
    REFRESH_TOKEN_INVALID: "REFRESH_TOKEN_INVALID",
    INVALID_INPUT: "INVALID_INPUT",
    MISSING_REQUIRED_FIELD: "MISSING_REQUIRED_FIELD",
    INVALID_FORMAT: "INVALID_FORMAT",
    UNEXPECTED_ERROR: "UNEXPECTED_ERROR",
    NOT_FOUND: "NOT_FOUND",
    DUPLICATE_ENTRY: "DUPLICATE_ENTRY",
    ACTION_NOT_ALLOWED:"ACTION_NOT_ALLOWED",
    PAYMENT_FAILED:"PAYMENT_FAILED"
  };
  
  Object.freeze(ERROR_CODES);
  
  module.exports = ERROR_CODES;
  